apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app-deployment
spec:
  type: NodePort
  selector:
    app: app-deployment
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30080
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: app-service-clusterip
  labels:
    app: app-deployment
spec:
  type: ClusterIP
  selector:
    app: app-deployment
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000 